AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "Stack com recursos para iserir um json no S3"
Parameters:
  Environment:
    Type: String
    Default: development
    AllowedValues: [development]
Mappings:
  Environments:
    development:
      ResourceSufix: development
      QueueSufix: Development
      SecurityGroupId: sg-0b8f9e8784efe46d5
      AnotaAiDesafioPrivateAppKey: secrets://anotaaidesafio/development?private_app_key
      AnotaAiDesafioPrivateAppSecret: parameters://anotaaidesafio/development?private-app/secret

Globals:
  Function:
    Runtime: python3.9
    MemorySize: 256
    Timeout: 600
    Layers:
      - Ref: DepLayer
    Tags:
      env: !FindInMap [ Environments, !Ref Environment, EnvTag ]
      project: "anota-ai"
    Environment:
      Variables:
        ENVIRONMENT: !Ref Environment
Resources:
  CatalogUpdateV2DLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !join [ "", [ "CatalogUpdateV2DLQ", !FindInMap [ Environments, !Ref Environment, QueueSufix ], ".fifo"] ]
      FifoQueue: true

  CatalogUpdateV2Queue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !join [ "", ["CatalogUpdateV2Queue", !FindInMap [ Environments, !Ref Environment, QueueSufix ], ".fifo"] ]
      FifoQueue: true
      ContentBasedDeduplication: true
      visibilityTimeout: 120
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt CatalogUpdateV2DLQ.Arn
        maxReceiveCount: 3

  CatalogEmitConsumerLoadFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src
      Handler: loaders.catalog_emit_consumer_load.lambda_handler
      FunctionName: !Join [ "-", [ "catalog-emit-consumer-load", !FindInMap [ Environments, !Ref Environment, ResourceSufix ] ] ]
      Timeout: 60
      Policies:
        - AWSLambda_FullAccess
        - AmazonSQSFullAccess
        - AmazonSSMReadOnlyAccess
        - SecretsManagerReadWrite
      VpcConfig:
        SecurityGroupIds:
          - !FindInMap [ Environments, !Ref Environment, SecurityGroupId ]
        SubnetIds:
          - !FindInMap [ Environments, !Ref Environment, SubnetId ]
      Events:
        CatalogUpdateV2Queue:
          Type: SQS
          Properties:
            Queue: !GetAtt CatalogUpdateV2Queue.Arn
            BatchSize: 1
            FunctionResponseTypes:
              - ReportBatchItemFailures