name: Deploy Application Anota-ai-desafio

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-2"

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install AWS SAM CLI
        run: |
          curl -L "https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip" -o sam.zip
          unzip sam.zip -d sam
          sudo mv sam/* /usr/local/bin/
          sam --version

      - name: Package AWS SAM application
        run: sam package --template-file template.yaml --output-template-file packaged.yaml --s3-bucket anotai-test

      - name: Deploy AWS SAM application
        run: sam deploy --template-file packaged.yaml --stack-name anota-ai-desafio --capabilities CAPABILITY_IAM

