name: Deploy Application Anota-ai-desafio

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-2"

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install -r dep.txt -t dependencies/python

      - name: Install SAM CLI
        run: |
          pip install aws-sam-cli

      - name: Package SAM application
        run: |
          sam package --template-file template.yaml --output-template-file packaged.yaml --s3-bucket anotai-test
          echo "SAM Package completed successfully"

      - name: Cleanup
        run: |
          rm -f packaged.yaml

      - name: List files in temporary directory
        run: |
          ls -l 

      - name: Deploy SAM application
        run: |
          echo "Deploying SAM application..."
          aws cloudformation deploy --template-file /packaged.yaml --parameter-overrides Environment=development --stack-name anota-ai-desafio --capabilities CAPABILITY_IAM
          echo "SAM deployment completed successfully"

      - name: Print contents of packaged.yaml
        run: |
          cat packaged.yaml




      
