name: Deploy Application Anota-ai-desafio

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws_access_key_id: AKIA2NJQBFDVU32ZKFPM
          aws_secret_access_key: 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
          aws_region: "us-east-2"

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install -r dep.txt -t dependencies/python
          sam package --template-file template.yaml --output-template-file packaged.yaml --s3-bucket annotai-test-sam
