name: Deploy Application Anota-ai-desafio

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SAM CLI
        run: |
          curl -o /tmp/sam https://d1vvhvl2y92vvt.cloudfront.net/awscli-exe-linux-x86_64.zip
          unzip -d /tmp /tmp/sam
          sudo /tmp/aws/install

      - name: Configure AWS CLI
        run: |
          aws configure --profile deployment set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure --profile deployment set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure --profile deployment set region $AWS_DEFAULT_REGION

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install -r dep.txt -t dependencies/python
          sam package --template-file template.yaml --output-template-file packaged.yaml --s3-bucket annotai-test-sam
