name: Deploy Application Anota-ai-desafio

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install -r dep.txt -t dependencies/python

      - name: Install SAM CLI
        run: |
          pip install aws-sam-cli

      - name: Build SAM application
        run: |
          sam build

      - name: Package SAM application
        run: |
          sam package --output-template-file packaged.yaml --s3-bucket anotai-test-sam

      - name: Deploy SAM application
        run: |
          sam deploy --template-file packaged.yaml --stack-name anota-ai-desafio --capabilities CAPABILITY_IAM




      
